# Payment service deployment workflow
name: Deploy Payment Service

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches:
    - 'main'
    paths:
    - 'services/payment/**'
    - '.github/workflows/payment.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v4
    
    - name: run tests
      run: |
        cd services/payment
        go test ./...

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        project_id: ${{ secrets.GOOGLE_PROJECT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev
        docker build -t asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/pandora/payment:latest ./services/payment
        docker push asia-southeast1-docker.pkg.dev/$GOOGLE_PROJECT/pandora/payment:latest